export const toNumber = (price) => {
  if (!price) return 0;
  const isNegative = price.toString().trim().startsWith("-");
  const value = parseFloat(price.toString().replace(/[^0-9.]/g, ""));
  return isNegative ? -value : value;
};
export const columnsOfSheet = [
  { data: "Order#", title: "Order#" },
  { data: "Charged Date", title: "Charged Date" },
  { data: "Lead Source", title: "Lead Source" },
  { data: "Procured By", title: "Procured By" },
  { data: "Order Date", title: "Order Date" },
  { data: "Refund Date", title: "Refund Date" },
  { data: "Sales Agent", title: "Sales Agent" },
  { data: "Invoice#", title: "Invoice#" },
  { data: "Invoice Link", title: "Invoice Link" },
  { data: "Order Source", title: "Order Source" },
  { data: "Payment Status", title: "Payment Status" },
  { data: "Brands", title: "Brands" },
  { data: "Category", title: "Category" },
  { data: "part#", title: "part#" },
  { data: "Qty", title: "Qty" },
  { data: "Condition", title: "Condition" },
  { data: "Shipping A/C", title: "Shipping A/C" },
  { data: "Bill to address", title: "Bill to address" },
  { data: "Ship to address", title: "Ship to address" },
  { data: "City", title: "City" },
  { data: "State", title: "State" },
  { data: "Country", title: "Country" },
  { data: "Carrier", title: "Carrier" },
  { data: "Tracking", title: "Tracking#" },
  { data: "Status", title: "Status" },
  { data: "Reasons (IF any)", title: "Reasons (IF any)" },
  { data: "Customer", title: "Customer" },
  { data: "Customer Company", title: "Customer Company" },
  { data: "Email", title: "Email" },
  { data: "Phone", title: "Phone" },
  { data: "Price", title: "Price" },
  { data: "Shipping", title: "Shipping" },
  { data: "Tax", title: "Tax" },
  { data: "Vendor", title: "Vendor" },
  { data: "Vendor order#", title: "Vendor order#" },
  { data: "Vendor Part#", title: "Vendor Part#" },
  { data: "CC/Paypal 4%", title: "CC/Paypal 4%" },
  { data: "Charged Vendor", title: "Charged Vendor" },
  { data: "Paid Via", title: "Paid Via" },
  { data: "Cost", title: "Cost" },
  { data: "Vendor Shipping", title: "Vendor Shipping" },
  { data: "Vendor Tax", title: "Vendor Tax" },
  { data: "Total Price", title: "Total Price" },
  { data: "Total Cost", title: "Total Cost" },
  { data: "Total Cost+4%", title: "Total Cost+4%" },
  { data: "Gross Profit", title: "Gross Profit" },
  { data: "Gross Profit-4%", title: "Gross Profit-4%" },
  { data: "Profit %", title: "Profit %" },
  { data: "Check/Invoice", title: "Check/Invoice" },
  { data: "Entry Check", title: "Entry Check" },
  { data: "Attached To Order", title: "Attached To Order" },
  { data: "Entry Reason", title: "Entry Reason" },
  { data: "Comment", title: "Comment" }
];

export const defaultOrder = {
  "Order#": "",
  "Charged Date": "",
  "Lead Source": "",
  "Procured By": "",
  "Order Date": "",
  "Refund Date": "",
  "Sales Agent": "",
  "Invoice#": "",
  "Invoice Link": "",
  "Order Source": "",
  "Payment Status": "",
  "Brands": "",
  "Category": "",
  "part#": "",
  "Qty": "",
  "Condition": "",
  "Shipping A/C": "",
  "Bill to address": "",
  "Ship to address": "",
  "City": "",
  "State": "",
  "Country": "",
  "Carrier": "",
  "Tracking": "",
  "Status": "",
  "Reasons (IF any)": "",
  "Customer": "",
  "Customer Company": "",
  "Email": "",
  "Phone": "",
  "Customer PO#": "",
  "Price": "",
  "Shipping": "",
  "Tax": "",
  "Vendor": "",
  "Vendor order#": "",
  "Vendor Part#": "",
  "CC/Paypal 4%": "",
  "Charged Vendor": "",
  "Paid Via": "",
  "Cost": "",
  "Vendor Shipping": "",
  "Vendor Tax": "",
  "Total Price": "",
  "Total Cost": "",
  "Total Cost+4%": "",
  "Gross Profit": "",
  "Gross Profit-4%": "",
  "Profit %": "",
  "Check/Invoice": "",
  "Entry Check": "",
  "Attached To Order": "",
  "Entry Reason": "",
  "Comment": ""
};